{
 "title": "MovieReviewHub",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "x": 0, "w": 24, "h": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service_name) (rate(http_server_request_duration_seconds_count[1m]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "95th percentile request latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "w": 24, "h": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (service_name, le) (rate(http_server_request_duration_seconds_bucket[1m])))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Server errors (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "w": 24, "h": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * ((sum by (service_name) (rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[1m])) or on(service_name) (0 * sum by (service_name) (rate(http_server_request_duration_seconds_count[1m])))) / clamp_min(sum by (service_name) (rate(http_server_request_duration_seconds_count[1m])), 0.000001))",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}