name: CI

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Start application
        run: docker compose up -d --build

      - name: Wait for API Gateway
        run: |
          echo "Waiting for API Gateway..."
          for i in {1..30}; do
            if curl --fail http://localhost:5000/movies; then
              echo "API Gateway is ready."
              exit 0
            fi
            echo "Waiting..."
            sleep 5
          done

          echo "API Gateway did not become ready."
          docker compose ps
          docker compose logs
          exit 1

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Publish AuthService
        run: dotnet publish services/AuthService/AuthService.csproj -c Release -o artifacts/AuthService

      - name: Publish MovieService
        run: dotnet publish services/MovieService/MovieService.csproj -c Release -o artifacts/MovieService

      - name: Publish ReviewService
        run: dotnet publish services/ReviewService/ReviewService.csproj -c Release -o artifacts/ReviewService

      - name: Publish WatchlistService
        run: dotnet publish services/WatchlistService/WatchlistService.csproj -c Release -o artifacts/WatchlistService

      - name: Publish NotificationService
        run: dotnet publish services/NotificationService/NotificationService.csproj -c Release -o artifacts/NotificationService

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: moviereviewhub-services
          path: artifacts/

      - name: Stop application
        if: always()
        run: docker compose down -v

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build